#!/usr/bin/env python3
"""Create a protected private PEGO instance skeleton.

The generated files live under private/. This script intentionally writes
generic placeholders only.
"""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PRIVATE = ROOT / "private"
TEMPLATES = ROOT / "pego" / "templates"


FILES: dict[str, str] = {
    "active-operating-brief.md": "active-operating-brief.md",
    "constitution/onboarding.md": "onboarding.md",
    "constitution/constitution.md": "constitution.md",
    "current-state/current-state.md": "current-state.md",
    "person/profile.md": "person-profile.md",
    "person/voice-and-taste.md": "voice-and-taste-model.md",
    "happiness/model.md": "happiness-model.md",
    "health/baseline.json": "health-baseline.json",
    "time/protected-time.md": "protected-time.md",
    "operator/operating-register.md": "operating-register.md",
    "governance/compliance-review-template.md": "compliance-review.md",
}


STATIC_FILES: dict[str, str] = {
    "README.md": """# Private PEGO Instance

This directory contains the protected private PEGO instance.

Do not commit private instance files.
""",
    "goals/README.md": """# Goals

Local private goals and goal strategies.
""",
    "directives/README.md": """# Directives

Local private PEGO directives.
""",
    "directives/candidates/README.md": """# Directive Candidates

Local private directive candidates generated by PEGO agents.
""",
    "directives/queues/README.md": """# Directive Queues

Local private synthesized directive queues.
""",
    "directives/command-responses/README.md": """# Command Responses

Local private next-directive command responses.
""",
    "onboarding/README.md": """# Onboarding

Protected private first-run intake packets and onboarding answers.
""",
    "directives/daily/README.md": """# Daily Directives

Local private daily directive packets.
""",
    "directives/weekly/README.md": """# Weekly Directives

Local private weekly operating plans.
""",
    "directives/monthly/README.md": """# Monthly Directives

Local private monthly strategy reviews.
""",
    "directives/escalations/README.md": """# Escalations

Local private high-impact directive packets.
""",
    "outcomes/README.md": """# Outcomes

Local private directive outcomes.
""",
    "outcomes/directives/README.md": """# Directive Outcomes

Local private directive outcome records.
""",
    "reviews/README.md": """# Reviews

Local private PEGO reviews.
""",
    "reviews/outcomes/README.md": """# Outcome Reviews

Local private outcome review packets.
""",
    "reviews/sessions/README.md": """# Session Reviews

Local private USER-mode session reviews.
""",
    "finance/README.md": """# Finance

Local private financial summaries, scenario assumptions, and outputs.

Raw source files should remain under private/_local/finance/.
""",
    "career/README.md": """# Career

Local private career and work strategy.
""",
    "health/README.md": """# Health

Local private health baseline, directives, and reviews.
""",
    "health/food-options/README.md": """# Food Options

Local private food options from manual inputs, home inventory, restaurants, grocery sources, nutrition lookups, or agent estimates.
""",
    "health/meal-decisions/README.md": """# Meal Decisions

Local private meal decisions and food directives.
""",
    "telemetry/README.md": """# Telemetry

Local private telemetry sources and summaries.
""",
    "writing/README.md": """# Writing

Local private writing samples, drafts, public-writing briefs, and publication reviews.
""",
    "writing/samples/README.md": """# Writing Samples

Local private writing samples PEGO may use to learn voice and style.
""",
    "writing/drafts/README.md": """# Drafts

Local private writing drafts.
""",
    "writing/briefs/README.md": """# Writing Briefs

Local private public-writing briefs.
""",
    "operator/README.md": """# Operator

Local private operator state, session logs, registers, and quickstart files.
""",
    "operator/briefs/README.md": """# Briefs

Local private operating briefs for USER mode.
""",
    "operator/sessions/README.md": """# Sessions

Local private intra-day session logs.
""",
    "attention/README.md": """# Attention

Local private attention options, leisure decisions, event decisions, and media outcomes.
""",
    "attention/decisions/README.md": """# Attention Decisions

Local private attention decisions such as watch live, multitask live, highlights later, score only, defer, skip, or escalate.
""",
    "governance/README.md": """# Governance

Local private governance constraints, reviews, and preflight outputs.
""",
    "governance/preflight/README.md": """# Preflight

Local private governance preflight outputs.
""",
    "governance/reviews/README.md": """# Governance Reviews

Local private formal governance review packets.
""",
}


def write_file(path: Path, content: str, force: bool) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    existed = path.exists()
    if existed and not force:
        return "skipped"
    path.write_text(content)
    return "written" if existed else "created"


def read_template(template_name: str) -> str:
    template_path = TEMPLATES / template_name
    return template_path.read_text()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="overwrite existing private files")
    args = parser.parse_args()

    results: list[tuple[str, str]] = []

    for relative_path, template_name in FILES.items():
        target = PRIVATE / relative_path
        content = read_template(template_name)
        status = write_file(target, content, args.force)
        results.append((relative_path, status))

    for relative_path, content in STATIC_FILES.items():
        target = PRIVATE / relative_path
        status = write_file(target, content, args.force)
        results.append((relative_path, status))

    (PRIVATE / "_local" / "finance").mkdir(parents=True, exist_ok=True)

    for relative_path, status in results:
        print(f"{status}: private/{relative_path}")

    print("ready: private/_local/finance")


if __name__ == "__main__":
    main()
